version: '3.8'
# database PostgreSQL version
services:
  postgresql:
    image: postgres:latest
    container_name: inventory-service-db
    environment:
      POSTGRES_USER: pisethsattya
      POSTGRES_PASSWORD: microservice
      POSTGRES_DB: inventory-service
    ports:
      - "4445:5432"
    volumes:
      - inventory-service_data:/var/lib/postgresql/data
    healthcheck: # Add health check
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d $POSTGRES_DB" ]
      interval: 10s
      retries: 5
      timeout: 5s
volumes:
  inventory-service_data:
