CREATE TABLE inventories
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sku_code VARCHAR(255),
    quantity INTEGER,
    CONSTRAINT pk_inventories PRIMARY KEY (id)
);
INSERT INTO inventories (sku_code, quantity)
VALUES
    ('iphone15', 100),
    ('samsung20', 150),
    ('xiaomi9', 200),
    ('oneplus6', 250),
    ('iphone16', 300);
